"""baseline_schema

Revision ID: c7239d1fc057
Revises:
Create Date: 2026-05-02 01:20:57.885448

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7239d1fc057"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "calls",
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column(
            "agent_id", sa.String(length=64), server_default="inbound-carrier-sales", nullable=False
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_seconds", sa.Integer(), nullable=False),
        sa.Column("carrier", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("load", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("negotiation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("analysis", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("sentiment", sa.String(length=16), nullable=False),
        sa.Column("transcript", sa.Text(), nullable=True),
        sa.Column("recording_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("call_id"),
    )
    op.create_index(op.f("ix_calls_agent_id"), "calls", ["agent_id"], unique=False)
    op.create_index(op.f("ix_calls_created_at"), "calls", ["created_at"], unique=False)
    op.create_index(op.f("ix_calls_outcome"), "calls", ["outcome"], unique=False)
    op.create_table(
        "loads",
        sa.Column("load_id", sa.String(length=32), nullable=False),
        sa.Column("origin", sa.String(length=128), nullable=False),
        sa.Column("destination", sa.String(length=128), nullable=False),
        sa.Column("pickup_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("equipment_type", sa.String(length=128), nullable=False),
        sa.Column("loadboard_rate", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("commodity_type", sa.Text(), nullable=False),
        sa.Column("num_of_pieces", sa.Integer(), nullable=False),
        sa.Column("miles", sa.Integer(), nullable=False),
        sa.Column("dimensions", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("load_id"),
    )
    op.create_index(op.f("ix_loads_destination"), "loads", ["destination"], unique=False)
    op.create_index(op.f("ix_loads_equipment_type"), "loads", ["equipment_type"], unique=False)
    op.create_index(op.f("ix_loads_origin"), "loads", ["origin"], unique=False)
    op.create_table(
        "negotiation_rounds",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("load_id", sa.String(length=32), nullable=False),
        sa.Column("round", sa.SmallInteger(), nullable=False),
        sa.Column("carrier_offer", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("broker_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "decided_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_negotiation_rounds_call_id"), "negotiation_rounds", ["call_id"], unique=False
    )
    op.create_index(
        "ix_negotiation_rounds_call_round", "negotiation_rounds", ["call_id", "round"], unique=False
    )
    op.create_index(
        op.f("ix_negotiation_rounds_load_id"), "negotiation_rounds", ["load_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "verifications",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("mc_number", sa.String(length=16), nullable=False),
        sa.Column("eligible", sa.Boolean(), nullable=False),
        sa.Column("carrier_name", sa.String(length=256), nullable=True),
        sa.Column("dot_number", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("raw_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verifications_checked_at"), "verifications", ["checked_at"], unique=False
    )
    op.create_index(
        op.f("ix_verifications_mc_number"), "verifications", ["mc_number"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_verifications_mc_number"), table_name="verifications")
    op.drop_index(op.f("ix_verifications_checked_at"), table_name="verifications")
    op.drop_table("verifications")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_negotiation_rounds_load_id"), table_name="negotiation_rounds")
    op.drop_index("ix_negotiation_rounds_call_round", table_name="negotiation_rounds")
    op.drop_index(op.f("ix_negotiation_rounds_call_id"), table_name="negotiation_rounds")
    op.drop_table("negotiation_rounds")
    op.drop_index(op.f("ix_loads_origin"), table_name="loads")
    op.drop_index(op.f("ix_loads_equipment_type"), table_name="loads")
    op.drop_index(op.f("ix_loads_destination"), table_name="loads")
    op.drop_table("loads")
    op.drop_index(op.f("ix_calls_outcome"), table_name="calls")
    op.drop_index(op.f("ix_calls_created_at"), table_name="calls")
    op.drop_index(op.f("ix_calls_agent_id"), table_name="calls")
    op.drop_table("calls")
    op.drop_table("agents")
    # ### end Alembic commands ###
